# Generated by Django 3.2.4 on 2021-07-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CarGuy',
        ),
    ]
